### ISSUE TITLE
选择cod-sam-vit-b.yaml训练时提示加载的模型权重和网络配置不一致，能否check或者update一下？

### ISSUE THREAD

**Issue by li-pengcheng** [tianrun-chen/SAM-Adapter-PyTorch#84]

**Comment by zrjisme** [comment]
同样的问题，希望大神指导一下怎么解决

**Comment by li-pengcheng** [comment]
> 同样的问题，希望大神指导一下怎么解决

用sam2_hiera_large.pt可以跑通

**Comment by Stangerine** [comment]
> > 同样的问题，希望大神指导一下怎么解决
> 
> 用sam2_hiera_large.pt可以跑通
我跑sam2_hiera_large.pt的时候，遇到这个问题，请问大佬有遇到过吗，萌新求助谢谢




Traceback (most recent call last):
  File "/data/zzq/object_tracking/SAM-Adapter-PyTorch/train.py", line 257, in <module>
    main(config, save_path)
  File "/data/zzq/object_tracking/SAM-Adapter-PyTorch/train.py", line 175, in main
    train_loss_G = train(train_loader, model)
  File "/data/zzq/object_tracking/SAM-Adapter-PyTorch/train.py", line 123, in train
    model.optimize_parameters()
  File "/data/zzq/object_tracking/SAM-Adapter-PyTorch/models/sam.py", line 395, in optimize_parameters
    self.forward()
  File "/data/zzq/object_tracking/SAM-Adapter-PyTorch/models/sam.py", line 245, in forward
    low_res_masks, iou_predictions,sam_output_tokens,object_score_logits, = self.mask_decoder(
  File "/home/a/miniconda3/envs/zzq_sot/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/a/miniconda3/envs/zzq_sot/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/zzq/object_tracking/SAM-Adapter-PyTorch/models/mmseg/models/sam/mask_decoder.py", line 137, in forward
    masks, iou_pred, mask_tokens_out, object_score_logits = self.predict_masks(
  File "/data/zzq/object_tracking/SAM-Adapter-PyTorch/models/mmseg/models/sam/mask_decoder.py", line 206, in predict_masks
    src = src + dense_prompt_embeddings
RuntimeError: The size of tensor a (128) must match the size of tensor b (256) at non-singleton dimension 1

**Comment by luxiangtaoya** [comment]
> > 同样的问题，希望大神指导一下怎么解决
> 
> 用sam2_hiera_large.pt可以跑通

请问需要多少显存？

**Comment by Lilyingying** [comment]
请问解决了吗

**Comment by tututututurana** [comment]
@Stangerine 请问解决了吗
